/* Generated by the Systemtap dtrace wrapper */


#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* TCL_PROC_ENTRY ( const char *name, int objc, struct Tcl_Obj **objv ) */
#if defined STAP_SDT_V1
#define TCL_PROC_ENTRY_ENABLED() __builtin_expect (proc__entry_semaphore, 0)
#define tcl_proc__entry_semaphore proc__entry_semaphore
#else
#define TCL_PROC_ENTRY_ENABLED() __builtin_expect (tcl_proc__entry_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_proc__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_PROC_ENTRY(arg1, arg2, arg3) \
DTRACE_PROBE3 (tcl, proc__entry, arg1, arg2, arg3)

/* TCL_PROC_RETURN ( const char *name, int code ) */
#if defined STAP_SDT_V1
#define TCL_PROC_RETURN_ENABLED() __builtin_expect (proc__return_semaphore, 0)
#define tcl_proc__return_semaphore proc__return_semaphore
#else
#define TCL_PROC_RETURN_ENABLED() __builtin_expect (tcl_proc__return_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_proc__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_PROC_RETURN(arg1, arg2) \
DTRACE_PROBE2 (tcl, proc__return, arg1, arg2)

/* TCL_PROC_RESULT ( const char *name, int code, const char *result, struct Tcl_Obj *resultobj ) */
#if defined STAP_SDT_V1
#define TCL_PROC_RESULT_ENABLED() __builtin_expect (proc__result_semaphore, 0)
#define tcl_proc__result_semaphore proc__result_semaphore
#else
#define TCL_PROC_RESULT_ENABLED() __builtin_expect (tcl_proc__result_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_proc__result_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_PROC_RESULT(arg1, arg2, arg3, arg4) \
DTRACE_PROBE4 (tcl, proc__result, arg1, arg2, arg3, arg4)

/* TCL_PROC_ARGS ( const char *name, const char *arg1, const char *arg2, const char *arg3, const char *arg4, const char *arg5, const char *arg6, const char *arg7, const char *arg8, const char *arg9 ) */
#if defined STAP_SDT_V1
#define TCL_PROC_ARGS_ENABLED() __builtin_expect (proc__args_semaphore, 0)
#define tcl_proc__args_semaphore proc__args_semaphore
#else
#define TCL_PROC_ARGS_ENABLED() __builtin_expect (tcl_proc__args_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_proc__args_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_PROC_ARGS(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) \
DTRACE_PROBE10 (tcl, proc__args, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)

/* TCL_PROC_INFO ( const char *cmd, const char *type, const char *proc, const char *file, int line, int level, const char *method, const char *class ) */
#if defined STAP_SDT_V1
#define TCL_PROC_INFO_ENABLED() __builtin_expect (proc__info_semaphore, 0)
#define tcl_proc__info_semaphore proc__info_semaphore
#else
#define TCL_PROC_INFO_ENABLED() __builtin_expect (tcl_proc__info_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_proc__info_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_PROC_INFO(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) \
DTRACE_PROBE8 (tcl, proc__info, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)

/* TCL_CMD_ENTRY ( const char *name, int objc, struct Tcl_Obj **objv ) */
#if defined STAP_SDT_V1
#define TCL_CMD_ENTRY_ENABLED() __builtin_expect (cmd__entry_semaphore, 0)
#define tcl_cmd__entry_semaphore cmd__entry_semaphore
#else
#define TCL_CMD_ENTRY_ENABLED() __builtin_expect (tcl_cmd__entry_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_cmd__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_CMD_ENTRY(arg1, arg2, arg3) \
DTRACE_PROBE3 (tcl, cmd__entry, arg1, arg2, arg3)

/* TCL_CMD_RETURN ( const char *name, int code ) */
#if defined STAP_SDT_V1
#define TCL_CMD_RETURN_ENABLED() __builtin_expect (cmd__return_semaphore, 0)
#define tcl_cmd__return_semaphore cmd__return_semaphore
#else
#define TCL_CMD_RETURN_ENABLED() __builtin_expect (tcl_cmd__return_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_cmd__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_CMD_RETURN(arg1, arg2) \
DTRACE_PROBE2 (tcl, cmd__return, arg1, arg2)

/* TCL_CMD_RESULT ( const char *name, int code, const char *result, struct Tcl_Obj *resultobj ) */
#if defined STAP_SDT_V1
#define TCL_CMD_RESULT_ENABLED() __builtin_expect (cmd__result_semaphore, 0)
#define tcl_cmd__result_semaphore cmd__result_semaphore
#else
#define TCL_CMD_RESULT_ENABLED() __builtin_expect (tcl_cmd__result_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_cmd__result_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_CMD_RESULT(arg1, arg2, arg3, arg4) \
DTRACE_PROBE4 (tcl, cmd__result, arg1, arg2, arg3, arg4)

/* TCL_CMD_ARGS ( const char *name, const char *arg1, const char *arg2, const char *arg3, const char *arg4, const char *arg5, const char *arg6, const char *arg7, const char *arg8, const char *arg9 ) */
#if defined STAP_SDT_V1
#define TCL_CMD_ARGS_ENABLED() __builtin_expect (cmd__args_semaphore, 0)
#define tcl_cmd__args_semaphore cmd__args_semaphore
#else
#define TCL_CMD_ARGS_ENABLED() __builtin_expect (tcl_cmd__args_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_cmd__args_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_CMD_ARGS(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) \
DTRACE_PROBE10 (tcl, cmd__args, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)

/* TCL_CMD_INFO ( const char *cmd, const char *type, const char *proc, const char *file, int line, int level, const char *method, const char *class ) */
#if defined STAP_SDT_V1
#define TCL_CMD_INFO_ENABLED() __builtin_expect (cmd__info_semaphore, 0)
#define tcl_cmd__info_semaphore cmd__info_semaphore
#else
#define TCL_CMD_INFO_ENABLED() __builtin_expect (tcl_cmd__info_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_cmd__info_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_CMD_INFO(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) \
DTRACE_PROBE8 (tcl, cmd__info, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)

/* TCL_INST_START ( const char *name, int depth, struct Tcl_Obj **stack ) */
#if defined STAP_SDT_V1
#define TCL_INST_START_ENABLED() __builtin_expect (inst__start_semaphore, 0)
#define tcl_inst__start_semaphore inst__start_semaphore
#else
#define TCL_INST_START_ENABLED() __builtin_expect (tcl_inst__start_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_inst__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_INST_START(arg1, arg2, arg3) \
DTRACE_PROBE3 (tcl, inst__start, arg1, arg2, arg3)

/* TCL_INST_DONE ( const char *name, int depth, struct Tcl_Obj **stack ) */
#if defined STAP_SDT_V1
#define TCL_INST_DONE_ENABLED() __builtin_expect (inst__done_semaphore, 0)
#define tcl_inst__done_semaphore inst__done_semaphore
#else
#define TCL_INST_DONE_ENABLED() __builtin_expect (tcl_inst__done_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_inst__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_INST_DONE(arg1, arg2, arg3) \
DTRACE_PROBE3 (tcl, inst__done, arg1, arg2, arg3)

/* TCL_OBJ_CREATE ( struct Tcl_Obj* obj ) */
#if defined STAP_SDT_V1
#define TCL_OBJ_CREATE_ENABLED() __builtin_expect (obj__create_semaphore, 0)
#define tcl_obj__create_semaphore obj__create_semaphore
#else
#define TCL_OBJ_CREATE_ENABLED() __builtin_expect (tcl_obj__create_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_obj__create_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_OBJ_CREATE(arg1) \
DTRACE_PROBE1 (tcl, obj__create, arg1)

/* TCL_OBJ_FREE ( struct Tcl_Obj* obj ) */
#if defined STAP_SDT_V1
#define TCL_OBJ_FREE_ENABLED() __builtin_expect (obj__free_semaphore, 0)
#define tcl_obj__free_semaphore obj__free_semaphore
#else
#define TCL_OBJ_FREE_ENABLED() __builtin_expect (tcl_obj__free_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_obj__free_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_OBJ_FREE(arg1) \
DTRACE_PROBE1 (tcl, obj__free, arg1)

/* TCL_TCL_PROBE ( const char *arg0, const char *arg1, const char *arg2, const char *arg3, const char *arg4, const char *arg5, const char *arg6, const char *arg7, const char *arg8, const char *arg9 ) */
#if defined STAP_SDT_V1
#define TCL_TCL_PROBE_ENABLED() __builtin_expect (tcl__probe_semaphore, 0)
#define tcl_tcl__probe_semaphore tcl__probe_semaphore
#else
#define TCL_TCL_PROBE_ENABLED() __builtin_expect (tcl_tcl__probe_semaphore, 0)
#endif
__extension__ extern unsigned short tcl_tcl__probe_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_TCL_PROBE(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) \
DTRACE_PROBE10 (tcl, tcl__probe, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)

