/*
Implement a program with the following code:

Compile the program with optimization level 0 and with the flag -g, then run the
 program with valgrind memcheck.

Repeat the compilation and running with valgrind after making one of the following
 modifications:

Comment out the initialization of as.
Comment out the freeing of as.
Amend the code with an additional free(as) at the end.
Discuss the respective valgrind output.

Please remember to remove the files vgcore.* generated by valgrind in order to not consume extraneous space on hard disc.

*/
#include <stdio.h>
#include <stdlib.h>

int
main()
{

int * as;
as = (int*)malloc(10*sizeof(int));
int sum = 0;

for ( int ix = 0; ix < 10; ++ix )
  as[ix] = ix;

for ( int ix = 0; ix < 10; ++ix )
  sum += as[ix];

printf("%d\n", sum);

//free(as);
}

/*
When commenting out the freeing Valgrind tells us that we are leaking. This in form
of 40 byters of defenetly lost memeory. It tells me that it is no errors and supresed
 errors when running with -s. When running with --leak-check=full It showed that the
  code had a error, which clearly is that the memory is not freed properly.
When I tried to comment out the int as i could not recomplile the file. It just gave
 me error so I could not run it with Valgrind.


*/
