St_and_he : Stack_and_heap_allo.c
	gcc -o St_and_he Stack_and_heap_allo.c

Red_mem_frag : Red_mem_frag.c 
	gcc -o Red_mem_frag Red_mem_frag.cp	 

writing_to_files : writing_to_files.c
	gcc -o writing_to_files writing_to_files.c
Parsing : Parsing.c
	gcc -o Parsing Parsing.c
	
writing_gbd : writing_to_files.c
	gcc -g -o writing writing_to_files.c

gdb_parsing : Parsing.c
	gcc -o gdb_parsing Parsing.c -g -Og -D NDEBU

naive : naive_bench.c
	gcc -o -Og naive naive_bench.c
